"""
Django settings for prop_house project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url

if os.path.isfile("env.py"):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Build path for template directory
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
ALLAUTH_TEMPLATES_DIR = os.path.join(BASE_DIR, "templates", "allauth")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# Check if is Heroku
IS_HEROKU_APP = "DYNO" in os.environ and "CI" not in os.environ

SECRET_KEY = os.environ.get("SECRET_KEY")
if IS_HEROKU_APP and not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in production")

if not SECRET_KEY:
    SECRET_KEY = "django-insecure-81+2!9qmoq61ogkt52vau-7bwv8=fr7@&&a*s8$-%y%5&hy8yl"

TINY_MCE_KEY = os.environ.get("TINY_MCE_KEY")

STRIPE_KEYS = {
    "stripe_sk": os.environ.get("STRIPE_SECRET"),
    "stripe_pk": os.environ.get("STRIPE_PUBLIC"),
}


if IS_HEROKU_APP:
    STRIPE_WH_SECRET = os.environ.get("STRIPE_WH")

else:
    STRIPE_WH_SECRET = os.environ.get("STRIPE_LOCAL_WH")

# Optional: Fail fast if keys are missing to avoid debugging headaches
if not STRIPE_KEYS["stripe_sk"] or not STRIPE_KEYS["stripe_pk"]:
    # Prevent app from running in broken state
    print(
        "WARNING: Stripe API keys are missing from the environment."
    )


if not STRIPE_WH_SECRET:
    # Left for brevity
    print(
        f"WARNING: Stripe Webhook Secret missing from environment({'Production' if IS_HEROKU_APP else 'Local'}) is unconfigured"
    )


DEBUG = not IS_HEROKU_APP


ALLOWED_HOSTS = [
    ".herokuapp.com",
    "127.0.0.1",
    "localhost",
    "testserver",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "anymail",
    # "allauth.socialaccount",
    "cloudinary",
    "view_breadcrumbs",
    "django_countries",
    "django_extensions",
    "django_filters",
    "djmoney",
    "stripe",
    "core",
    "accounts",
    "basket",
    "catalogue",
    "commerce",
    "warehouse",
]

if DEBUG:
    INSTALLED_APPS.append("django_erd_generator")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_permissions_policy.PermissionsPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "basket.middleware.BasketMiddleware",
]

if DEBUG:
    MIDDLEWARE.append(
        "prop_house.middleware.LocalHeaderDebugMiddleware"
    )

ACCOUNT_ADAPTER = "core.adapter.PropHouseAccountAdapter"

PERMISSIONS_POLICY = {
    "unload": ["self"],
}

ROOT_URLCONF = "prop_house.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            TEMPLATE_DIR,
            ALLAUTH_TEMPLATES_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Required by allauth
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "basket.context_processors.basket_context",
            ],
        },
    },
]

WSGI_APPLICATION = "prop_house.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
}

if "test" in sys.argv:
    DATABASES["default"]["ENGINE"] = "django.db.backends.sqlite3"

# CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net/",
    "https://*.herokuapp.com",
]

CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

# Session

SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_SERIALIZER = (
    "django.contrib.sessions.serializers.JSONSerializer"
)


# Ensure the cookie is accessible to your local dev environment
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))

EMAIL_HOST_USER = os.environ.get("GMAIL_USER")
EMAIL_HOST_PASSWORD = os.environ.get("GMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")


# Override the default allauth forms

ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm",
    "login": "accounts.forms.CustomLoginForm",
}

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND


ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Local development allows repeated signup testing
# against a single inbox without account cleanup.
ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_LOGIN_METHODS = {
    "username",
}

# Production uses unique emails and supports
# login via username or email.
if IS_HEROKU_APP:
    ACCOUNT_LOGIN_METHODS = {
        "username",
        "email",
    }
    ACCOUNT_UNIQUE_EMAIL = True
    EMAIL_TIMEOUT = 10


ACCOUNT_USERNAME_MIN_LENGTH = 4
LOGIN_URL = "/accounts/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

ACCOUNT_SIGNUP_FIELDS = [
    "username*",
    "email*",
    "password1*",
    "password2*",
]

# Signup Email
ACCOUNT_EMAIL_HTML_TEMPLATE_VARIABLES = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "PROP HOUSE // "

# Cloudinary settings

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": "df6l9qsox",
    "API_KEY": os.environ.get("CLOUDINARY_API"),
    "API_SECRET": os.environ.get("CLOUDINARY_SECRET"),
}

# This ensures uploaded files go to Cloudinary
DEFAULT_FILE_STORAGE = (
    "cloudinary_storage.storage.MediaCloudinaryStorage"
)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Build a path for static dir
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
