# Generated by Django 6.0.4 on 2026-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(
                default="",
                help_text="Snapshot of the product name at time of purchase",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OrderLine",
        ),
    ]
