# Generated by Django 6.0.4 on 2026-05-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_orderitem_product_name_delete_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="production_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
