# Generated by Django 6.0.4 on 2026-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0004_orderitem_end_date_orderitem_production_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
