# Generated by Django 6.0.4 on 2026-06-11 15:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_order_admin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address_line_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_line_2",
            field=models.CharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_contact_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_country",
            field=django_countries.fields.CountryField(
                default="GB", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_county",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_house_name_or_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone_number",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_town_or_city",
            field=models.CharField(default="", max_length=255),
        ),
    ]
