# Generated by Django 6.0.4 on 2026-05-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("commerce", "0002_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AV", "Available"),
                            ("OH", "On Hire"),
                            ("MA", "Maintenance"),
                            ("RE", "Retired"),
                        ],
                        default="AV",
                        max_length=2,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="catalogue.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HireRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField()),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                ("condition_on_out", models.TextField(blank=True)),
                ("condition_on_return", models.TextField(blank=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="commerce.orderitem",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_history",
                        to="warehouse.stockitem",
                    ),
                ),
            ],
        ),
    ]
