# Generated by Django 6.0.4 on 2026-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_membershiptier_user_membership_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="The Stripe Price API ID, for recurring subscription billing.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
