# Generated by Django 6.0.4 on 2026-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membershiptier_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="An array of feature strings.",
                null=True,
            ),
        ),
    ]
