# Generated by Django 6.0.4 on 2026-06-08 00:25

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_membershiptier_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Default", max_length=80
                    ),
                ),
                (
                    "delivery_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("phone_number", models.CharField(max_length=30)),
                (
                    "house_name_or_number",
                    models.CharField(max_length=255),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("town_or_city", models.CharField(max_length=255)),
                ("county", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=20)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="GB", max_length=2
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
