# Generated by Django 6.0.4 on 2026-05-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="line",
            name="production_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="line",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
