# Generated by Django 6.0.2 on 2026-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_line_price_at_addition_currency_alter_line_basket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
